mybatisGenerator:
  properties:
    javaFileEncoding: UTF-8
  datasource:
    type: mysql
    address: localhost:3306
    db: distribute?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  targetPackage:
    model: com.fanx.distribute.lock.distributelock.entity
    mapper: com.fanx.distribute.lock.distributelock.mapper
    javaXmlFilesSamePackage: false

  targetRuntime: MyBatis3
  mapperSuffixName: mapper
  java8: false
  disableExample: false

  plugins:
    comment: true
    lombok: true
    swagger: false
    mapperAnnotation: true
    serializable: false

  tables:
    - distribute_lock