package com.fanx.distribute.eventualconsistency.localmsg.mapper.db161;

import com.fanx.distribute.eventualconsistency.localmsg.entity.PaymentMsg;
import com.fanx.distribute.eventualconsistency.localmsg.entity.PaymentMsgExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface PaymentMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Jan 08 15:13:36 CST 2022
     */
    long countByExample(PaymentMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Jan 08 15:13:36 CST 2022
     */
    int deleteByExample(PaymentMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Jan 08 15:13:36 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Jan 08 15:13:36 CST 2022
     */
    int insert(PaymentMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Jan 08 15:13:36 CST 2022
     */
    int insertSelective(PaymentMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Jan 08 15:13:36 CST 2022
     */
    List<PaymentMsg> selectByExample(PaymentMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Jan 08 15:13:36 CST 2022
     */
    PaymentMsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Jan 08 15:13:36 CST 2022
     */
    int updateByExampleSelective(@Param("record") PaymentMsg record, @Param("example") PaymentMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Jan 08 15:13:36 CST 2022
     */
    int updateByExample(@Param("record") PaymentMsg record, @Param("example") PaymentMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Jan 08 15:13:36 CST 2022
     */
    int updateByPrimaryKeySelective(PaymentMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_msg
     *
     * @mbg.generated Sat Jan 08 15:13:36 CST 2022
     */
    int updateByPrimaryKey(PaymentMsg record);
}